apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: fastclam

  name: fastclam

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastclam

  template:
    metadata:
      labels:
        app: fastclam

    spec:
      containers:
        - image: ghcr.io/wgbh-mla/fastclam:main
          name: fastclam
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: '/m'
              name: media
          resources:
            limits:
              cpu: '1000m'
              memory: '1Gi'
            requests:
              cpu: '100m'
              memory: '100Mi'
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
